version: '3.7'
services:
  nest:
    container_name: nest_prisma
    build: .
    tty: true
    ports:
      - '13000:3000'
    volumes:
      - './app:/usr/src/app'
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=4000
      - DB_USER=root
      - DB_NAME=test
      - DATABASE_URL=mysql://root@host.docker.internal:4000/test
